### PR TITLE
fix #200: redeclaration of layout fragments in nested decoration hierarchies must produce the expected result

### LINKED ISSUE #200: Redeclaring a layout fragment in a decoration template that is part of a hierarchy of nested templates yields the wrong results
Having a template in a hierarchy of nested templates, that redeclares a layout fragment that was already declared in the decorated base template at the root of the hierarchy, and with the content template once again declaring the same layout fragment, the fragment declared by the decorated template will be used instead of that from the content template.

Example

```

# Test a deep layout hierarchy (3 levels) with redeclaration of layout fragments.

%TEMPLATE_MODE HTML


%INPUT
<!DOCTYPE html>
<html xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout"
	layout:decorate="~{Parent}">
<head>
	<title>Page title</title>
	<script src="child-script.js"></script>
</head>
<body>
	<div layout:fragment="content">
		<p>Page content</p>
	</div>
	<footer layout:fragment="footer">
	  <p>Page footer</p>
	</footer>
</body>
</html>


%INPUT[Parent]
<!DOCTYPE html>
<html xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout"
	layout:decorate="~{Grandparent}">
<head>
	<script src="parent-script.js"></script>
</head>
<body>
	<section layout:fragment="section">
		<header>
			<h1>My website</h1>
		</header>
		<div layout:fragment="content">
			<p>Parent content</p>
		</div>
	</section>
	<!-- parent redeclares footer -->
	<footer layout:fragment="footer">
		<p>Parent footer</p>
	</footer>
</body>
</html>


%INPUT[Grandparent]
<!DOCTYPE html>
<html xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout">
<head>
	<script src="grandparent-script.js"></script>
</head>
<body>
	<section layout:fragment="section">
		<p>Grandparent section</p>
	</section>
	<footer layout:fragment="footer">
		<p>Grandparent footer</p>
	</footer>
</body>
</html>


%OUTPUT
<!DOCTYPE html>
<html>
<head>
	<title>Page title</title>
	<script src="grandparent-script.js"></script>
	<script src="parent-script.js"></script>
	<script src="child-script.js"></script>
</head>
<body>
	<section>
		<header>
			<h1>My website</h1>
		</header>
		<div>
			<p>Page content</p>
		</div>
	</section>
	<footer>
		<p>Page footer</p>
	</footer>
</body>
</html>
```

The above will fail with the following output

```
Obtained:
[ion>
	<footer>
		<p>Parent footer</p>
	</footer>
</bo]
at line 19 col 6, but expected:
[ion>
	<footer>
		<p>Page footer</p>
	</footer>
```

A remedy for this is to change the FragmentProcessor to use the last fragment instead of the first, e.g.

```
def fragment = fragments.size() == 1 ? fragments.first() : fragements.last()
```

Doing so will make the tests for infinite loops fail, so this might be more involved.

### PR DESCRIPTION
**Pull request by silkentrance**
- also changes the way that top down processing (aka include/replace/insert) and standard processing works in terms of handling the fragments stored in the FragmentMap

- existing InfiniteLoop tests for include/replace/insert have been modified in order to show that they will still work with referenced fragments from external templates. embedding the same fragments in the same template still works

### CODE REVIEW

**Comment by ultraq** [comment]
Thank you for taking a deep dive into the issue and submitting a PR.  I'll definitely give this a look in the coming days.

As you've noted, it does change the order that fragments are retrieved from the map that's created by working through the templates, and over time some developers may have built things to rely on that behaviour.  From a glance what you're solving does line up more with how inheritance is in object-oriented languages, so I think it is a good change, but maybe at least requires a minor version bump (so 2.5.0) instead of just a patch (2.4.x).  Anyway, it's something I'll have to weigh up.

File: source/nz/net/ultraq/thymeleaf/fragments/FragmentMap.groovy [hunk 1]
```diff
@@ -45,18 +45,43 @@ class FragmentMap extends HashMap<String,List<IModel>> {
...
+
+	private static void setForNodeInternal(IContext context, IElementModelStructureHandler structureHandler,
+		Map<String,List<IModel>> fragments, boolean isIncludeProcessing) {
 
 		structureHandler.setLocalVariable(FRAGMENT_COLLECTION_KEY,
 			get(context).inject(fragments.clone()) { accumulator, fragmentName, fragmentList ->
 				if (accumulator[fragmentName]) {
 					accumulator[fragmentName] += fragmentList
+					if (isIncludeProcessing) {
+						accumulator[fragmentName] = ((List) accumulator[fragmentName]).reverse()
```
Comment (ultraq) [inline source/nz/net/ultraq/thymeleaf/fragments/FragmentMap.groovy]: Groovy adds [an in-place `reverse` method](https://docs.groovy-lang.org/latest/html/groovy-jdk/java/util/List.html#reverse(boolean)) that, when passed `true`, lets you mutate the list, so that could be used here to simplify the line a bit:

```suggestion
						accumulator[fragmentName].reverse(true)
```

File: tests/nz/net/ultraq/thymeleaf/tests/includes/Include-NestedFragmentInfiniteLoop.thtest [hunk 2]
```diff
@@ -8,29 +8,26 @@
...
+		<div layout:fragment="comment-details">Default comment details</div>
+	</div>
+
 %OUTPUT
 <html>
 <body>
-	<div>
-		Comment structure
-		<div>Default comment details</div>
-	</div>
```
Comment (ultraq) [inline tests/nz/net/ultraq/thymeleaf/tests/includes/Include-NestedFragmentInfiniteLoop.thtest]: I'm a bit worried about the changes that were required to the "infinite loop" test files, as I think the change makes them different enough from the original bug that was raised: https://github.com/ultraq/thymeleaf-layout-dialect/issues/178  Do the changes made to `FragmentMap` alter the behaviour here?

File: source/nz/net/ultraq/thymeleaf/fragments/FragmentMap.groovy [hunk 3]
```diff
@@ -45,18 +45,43 @@ class FragmentMap extends HashMap<String,List<IModel>> {
...
+	 * @param structureHandler
+	 * @param fragments The new fragments to add to the map.
+	 */
+	static void setForNodeIncludeProcessing(IContext context, IElementModelStructureHandler structureHandler,
+		Map<String,List<IModel>> fragments) {
+		setForNodeInternal(context, structureHandler, fragments, true)
+	}
+
+	private static void setForNodeInternal(IContext context, IElementModelStructureHandler structureHandler,
+		Map<String,List<IModel>> fragments, boolean isIncludeProcessing) {
```
Comment (ultraq) [inline source/nz/net/ultraq/thymeleaf/fragments/FragmentMap.groovy]: In Groovy you can set default values for method parameters so you don't need to overload methods or make slightly different ones with additional flags here and there.  So this can all be simplified by adding `boolean isIncludeProcessing = false` as a new method parameter to the `setForNode` method:

```suggestion
		Map<String,List<IModel>> fragments, boolean isIncludeProcessing = false) {
```

The files that then call `setForNodeIncludeProcessing` can be put back to `setForNode`, but then add `true` as a 4th parameter to that call.

File: source/nz/net/ultraq/thymeleaf/fragments/FragmentProcessor.groovy [hunk 4]
```diff
@@ -84,7 +84,7 @@ class FragmentProcessor extends AbstractAttributeTagProcessor {
 
 		// Replace the tag body with the fragment
 		if (fragments) {
-			def fragment = fragments.first()
+			def fragment = fragments.size() == 1 ? fragments.first() : fragments.last()
```
Comment (ultraq) [inline source/nz/net/ultraq/thymeleaf/fragments/FragmentProcessor.groovy]: This can be changed to `fragments.last()` and will have the same effect.

**Comment by silkentrance** [comment]
I have not yet found the time to work on this. I will come back to this ASAP.

**Comment by ultraq** [comment]
As per the linked bug, I'll merge this PR and apply my suggestions atop it (then get it into the main branch since the code has moved quite a bit since this was opened).  Thanks again for the PR! 🙂
